# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a41ecc00424f851fb66b8d9c33dbafe65c80ea43fd8fc87aecf21df5060e7a394e57769ed0c738e711ba55ddd9c1487f8e416808408949bcf9de73843e4c6c93

test:
  secret_key_base: 26d196654d1b68827aba3705caf7913051e5d608116fe5b3fdf3927fe786621fdaa235e09d41d90d792cdd78a00bb5121dfd31187440b7b69a8e4fca4482401a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
